### ISSUE TITLE
[Question] Anyone here using this Dockerfile on a VPS? 

### ISSUE THREAD

**Issue by nrosenw** [DomiStyle/docker-eldewrito#4]
I'd just like to know someone's virtual hardware specifications, OS, and how well the container is running. I wanted to test it on my super cheap VPS but I guess that provider actually blocks Docker, oops. If it comes down to it I might just go back to my old VPS provider and attempt run everything from the Dockerfile manually.

Edit: As Domi suggested me stating, I'm in the US. Not sure if this other bit of info helps, but I was looking for a VPS in Dallas or Chicago so that those on both coasts wouldn't have too much trouble with latency.

**Comment by DomiStyle** [comment]
You should probably add where you're from.

Usually you're going to have the best luck with dedicated servers.
Since Docker runs containers it isn't always that easy to run Docker inside of another container, which is what VPS stands for many times. Make sure you find out the underlying technology your hoster uses. For example, KVM means you get a full VM and can use Docker without issues. OpnVZ/LXC/LXD or anything else named after "container" usually means you get a container. They're cheaper but require special setup from the hoster to get Docker working inside of it, most of them don't bother.

So make sure you find a hoster that provides real VMs or supports Docker directly and you're good.
